version: '3'
services:
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
#    container_name: elasticsearch
#    environment:
#      - discovery.type=single-node
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    ports:
#      - 9200:9200
#      - 9300:9300
#    volumes:
#      - esdata:/usr/share/elasticsearch/data
#    networks:
#      - es_network

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 292003
      MYSQL_DATABASE: workmanagement
      MYSQL_USER: quangduong
      MYSQL_PASSWORD: 292003
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - es_network

  spring-boot-app:
    container_name: work-management-backend
    restart: always
    build: .
    ports:
      - 8081:8081
    depends_on:
#      - elasticsearch
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: workmanagement
      DB_USER: quangduong
      DB_PASSWORD: 292003
#      ES_HOST: host.docker.internal
#      ES_PORT: 9300
#      ES_CLUSTERNAME: docker-cluster
    networks:
      - es_network

volumes:
#  esdata:
  mysql_data:

networks:
  es_network:
    driver: bridge
